"""
Django settings for SogandAghsat project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--q1v)rk0#9xchx^7ix*i0$-iosiiik=drvzk^i#lli_p_n5@)0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aghsat',
    'django_jalali',
    'django_crontab',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "SogandAghsat.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SogandAghsat.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CRONJOBS = [
    ('0 10 * * *', 'django.core.management.call_command', ['send_reminders']),
]
# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
SMS_USERNAME = 'aria100907'
SMS_PASSWORD = '9197608060'
SMS_FROM_NUMBER = '+98500043449'
SMS_API_URL = 'https://skyariacp.com/webservice/url/send.php'
SMS_API_KEY = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNDI2YTI4MjBiNzkzNzA1YWY3YjdkYTBhMTQ1YjA4ZDIyYzU2ZGMwMzY4NWY4ZThkNWEyZWJjZjVlNjk1YmZmMDk5YTE5MTUwYThiMDE4NDYiLCJpYXQiOjE3NTk3Mzk0OTEuODUzNDczLCJuYmYiOjE3NTk3Mzk0OTEuODUzNDczLCJleHAiOjE3OTEyNzU0OTEuODUzNDczLCJzdWIiOiIxNzkxNSIsInNjb3BlcyI6IltdIn0.rFK2stpDQRYg8NNrAxpqdLLWRl3ZW43XX28cHq31cfNYMsxqL22ZaysQPAaGTHVeefeb31shcxPCCzcKTMRexpxksmQt6PHxl4Imdbfs9gFasX21I-L1uMHql3BXGVqH6pBckPtzruOM7RBxDScnIpoeLm98M1gWsazQgn3gcF0H9QuVdzqP17gUaT2xdBr8syfdcyO8C69ik23DTZOo-BfFlhPChaUJiG-AeFS47PgBAuHvkhm_xzuQv5oFn806enEufHgJR03XSMD5x6AMwobxhzjV93_IT-PjOuzIQBW5S3sAzg5L5eaHfgrriT5wHbQO-pPlHjuGQLY8rGB9o4WB7nnJXlAbW-Vc1tTZXn0urL0lauWEUa-Qwa8kj7yMnu1UsbC4Iz4rG9UA8zH8CaVbXBHCUPqXybLcLQ570zKUrECUG_6Yx4zYqudhv1kcqylJv-3y4r1ooDZeUCF55jTNcmcXJ8F5GxmA2XMaFBzjGhF1eub01FrHut5JH9ICrvf32ykV1ixkdA8-uEJTsY-iUWfpTC6Md6coerEz07te8C7EK1L8Q_5pSbX7LsTOeMJaMJbjwM-QvE-y-ay87bk0m-KGp7I5ynoSC8Pz2wsb7YAGqfZdCuQzB5Wyqdwv-78jVHUw70hLJbEEnfRiDTOWU-hH_ZC5I-RvYlPbNmE'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'


# SogandAghsat/settings.py

# در انتهای فایل، بخش SMS Configuration را به‌روزرسانی کنید:

# ========================================
# SMS Configuration
# ========================================
SMS_API_URL = 'https://skyariacp.com/webservice/url/send.php'
SMS_USERNAME = 'aria100907'
SMS_PASSWORD = '9197608060'
SMS_SENDER_NUMBER = '9890005354'  # شماره اختصاصی ارسال‌کننده شما (مثلاً 10001234 یا 3000...)
SMS_CONFIG = {
    'API_URL': 'https://skyariacp.com/webservice/url/send.php',
    'USERNAME': 'aria100907',
    'PASSWORD': '9197608060',
    'API_KEY': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiZThjZGFlNzZiMThmMjJkYTA3NDk3NDA2NzY1OGMxMmVlNzUwMWQyNzBmNzUyY2QzNWY4MDhmNTFmNDMyZmYzNGY1MTQ4YTljMTA1NjkzZTIiLCJpYXQiOjE3NTk3NTAyOTkuODE4ODcyLCJuYmYiOjE3NTk3NTAyOTkuODE4ODcyLCJleHAiOjE3OTEyODYyOTkuODE4ODcyLCJzdWIiOiIxNzkxNSIsInNjb3BlcyI6IltdIn0.KpBphiA4urDEeiesPRnAUiYQAPT-G8xicIcpLKTLNHsdqAnP65WErFN-SNObNL9_jbUe1_y3IxLm2WJ6KJ4wAjL7D8qDGSWWjqal8OR6a8xuvUWrsri--Chx__YlP4Ukn1MohB8La2bb0dmY17Fbqq5XkW6crOMGQ22pEOuZD3wz6kR9pagk48NFuWy5o-gvlZBxLLulf1y9pUbqEvSlSolu-2VE8Iwqqa9GgDFaWAdsMlbXrZVMz3LxgZ7MCVCl10P5eEHC0pSMC7wAqwLbYZrbdF6HtJDy_x_9_jshayExdOyRnBTn0QJ_9YhBtXYYBp6T2GYLrzyU0ivsiw82Hv086r4YYt_qirXX4IC586v0V3Waw0LZzF6sIuA-f1ysW1A3SIXK2kMty8A3Xjv8ieYlQmycXEs_Di5el244wzjTvC_tlSO2qmzOwvLv3UqSjXvaylFS80qifgQg6mof5yPcVJyiEAoE5rieS-w3jirxWQXx6D99VIge6RwJH0FMwZJcTZrmZJyqVX3Z2v5p95yrGsmrg5JuK04dyKLmznoDhXLFUsW1AK-1YQ5knTOzKIJyrIGEEYX1Xfl5qxZN69kNXGWTMkM6H0JoYwK9MD7CO4K3H8ObmtLQdqZV7JVBUGlgbfwwdFnuPkyKtfmW8AsCu9t6Fq_o6VDrr0-sk2Y',
    'FROM_NUMBER': '9890005354',  # ⚠️ شماره فرستنده خود را اینجا وارد کنید
}
# ========================================
# Logging Configuration
# ========================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'sms.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'aghsat': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
